id: AE822E99A
title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the Tsok
  Feast Offering to Venerable and Exalted Vajrayoginī'
type: translation
pechas:
- IABAFFF2C
- IABB3D3E1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:38:06.171985
  last_modified_at: 2023-01-04 12:38:06.171992
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IABAFFF2C/DD51: BED9
  IABB3D3E1/7F33: BED9
